export interface Tool {
  slug: string;
  name: string;
  category: string;
  description: string;
  keywords: string[];
  icon: string;
  faq: { question: string; answer: string }[];
  relatedTools: string[];
}

export const categories = [
  { id: 'basic', name: 'Basic Calculators', icon: '🔢' },
  { id: 'finance', name: 'Finance Calculators', icon: '💰' },
  { id: 'india', name: 'India Tools', icon: '🇮🇳' },
  { id: 'student', name: 'Student Tools', icon: '📚' },
  { id: 'health', name: 'Health & Fitness', icon: '💪' },
  { id: 'fun', name: 'Fun Tools', icon: '🎉' },
  { id: 'converter', name: 'Unit Converters', icon: '🔄' },
  { id: 'advanced', name: 'Advanced', icon: '📊' },
];

export const tools: Tool[] = [
  // Basic Calculators
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    category: 'basic',
    description: 'Calculate your exact age in years, months, and days from your date of birth',
    keywords: ['age calculator', 'exact age', 'age today', 'date of birth'],
    icon: '🎂',
    faq: [
      { question: 'How is age calculated?', answer: 'Age is calculated by finding the difference between your birth date and today\'s date in years, months, and days.' },
      { question: 'Can I calculate age for any date?', answer: 'Yes, you can calculate age for any past or future date.' },
    ],
    relatedTools: ['date-difference', 'birthday-countdown', 'time-calculator'],
  },
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    category: 'basic',
    description: 'Calculate percentages easily - find what percent one number is of another',
    keywords: ['percentage calculator', 'percent calculation', 'what percent'],
    icon: '💯',
    faq: [
      { question: 'How to calculate percentage?', answer: 'Divide the part by the whole and multiply by 100.' },
    ],
    relatedTools: ['discount-calculator', 'profit-loss-calculator'],
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    category: 'basic',
    description: 'Calculate discount amount and final price after discount',
    keywords: ['discount calculator', 'sale price', 'discount percentage'],
    icon: '🏷️',
    faq: [],
    relatedTools: ['percentage-calculator', 'profit-loss-calculator'],
  },
  {
    slug: 'profit-loss-calculator',
    name: 'Profit & Loss Calculator',
    category: 'basic',
    description: 'Calculate profit or loss percentage and amount',
    keywords: ['profit calculator', 'loss calculator', 'profit margin'],
    icon: '📈',
    faq: [],
    relatedTools: ['percentage-calculator', 'discount-calculator'],
  },
  {
    slug: 'average-calculator',
    name: 'Average Calculator',
    category: 'basic',
    description: 'Calculate the average (mean) of multiple numbers',
    keywords: ['average calculator', 'mean calculator', 'average of numbers'],
    icon: '📊',
    faq: [],
    relatedTools: ['percentage-calculator'],
  },
  {
    slug: 'ratio-calculator',
    name: 'Ratio Calculator',
    category: 'basic',
    description: 'Calculate ratios and proportions easily',
    keywords: ['ratio calculator', 'proportion calculator', 'ratio solver'],
    icon: '⚖️',
    faq: [],
    relatedTools: ['percentage-calculator'],
  },
  {
    slug: 'time-calculator',
    name: 'Time Calculator',
    category: 'basic',
    description: 'Add, subtract, and convert time durations',
    keywords: ['time calculator', 'time add', 'time difference'],
    icon: '⏰',
    faq: [],
    relatedTools: ['date-difference', 'age-calculator'],
  },
  {
    slug: 'date-difference',
    name: 'Date Difference Calculator',
    category: 'basic',
    description: 'Calculate the difference between two dates in days, weeks, months',
    keywords: ['date difference', 'days between dates', 'date calculator'],
    icon: '📅',
    faq: [],
    relatedTools: ['age-calculator', 'time-calculator'],
  },
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    category: 'basic',
    description: 'Calculate simple interest on loans and investments',
    keywords: ['simple interest', 'SI calculator', 'interest calculation'],
    icon: '💵',
    faq: [],
    relatedTools: ['compound-interest-calculator', 'emi-calculator'],
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    category: 'basic',
    description: 'Calculate compound interest with annual, monthly, or daily compounding',
    keywords: ['compound interest', 'CI calculator', 'compound growth'],
    icon: '💹',
    faq: [],
    relatedTools: ['simple-interest-calculator', 'sip-calculator'],
  },

  // Finance Calculators
  {
    slug: 'emi-calculator',
    name: 'EMI Calculator',
    category: 'finance',
    description: 'Calculate EMI for home loan, car loan, personal loan in India 2026',
    keywords: ['emi calculator', 'loan emi', 'monthly payment', 'india 2026'],
    icon: '🏦',
    faq: [
      { question: 'What is EMI?', answer: 'EMI (Equated Monthly Installment) is a fixed payment amount made by a borrower to a lender at a specified date each calendar month.' },
    ],
    relatedTools: ['loan-calculator', 'simple-interest-calculator'],
  },
  {
    slug: 'loan-calculator',
    name: 'Loan Calculator',
    category: 'finance',
    description: 'Calculate loan amount, interest, and total repayment',
    keywords: ['loan calculator', 'loan payment', 'borrowing calculator'],
    icon: '💳',
    faq: [],
    relatedTools: ['emi-calculator', 'simple-interest-calculator'],
  },
  {
    slug: 'sip-calculator',
    name: 'SIP Calculator',
    category: 'finance',
    description: 'Calculate monthly SIP returns and wealth gained in India 2026',
    keywords: ['sip calculator', 'monthly investment', 'mutual fund returns', 'india'],
    icon: '📈',
    faq: [],
    relatedTools: ['compound-interest-calculator', 'fd-calculator'],
  },
  {
    slug: 'fd-calculator',
    name: 'FD Calculator',
    category: 'finance',
    description: 'Calculate Fixed Deposit maturity amount and interest earned',
    keywords: ['fd calculator', 'fixed deposit', 'maturity amount'],
    icon: '🏛️',
    faq: [],
    relatedTools: ['rd-calculator', 'sip-calculator'],
  },
  {
    slug: 'rd-calculator',
    name: 'RD Calculator',
    category: 'finance',
    description: 'Calculate Recurring Deposit maturity amount and returns',
    keywords: ['rd calculator', 'recurring deposit', 'monthly deposit'],
    icon: '💰',
    faq: [],
    relatedTools: ['fd-calculator', 'sip-calculator'],
  },
  {
    slug: 'retirement-calculator',
    name: 'Retirement Calculator',
    category: 'finance',
    description: 'Plan your retirement corpus and monthly savings needed',
    keywords: ['retirement calculator', 'retirement planning', 'corpus calculation'],
    icon: '🏖️',
    faq: [],
    relatedTools: ['sip-calculator', 'investment-calculator'],
  },
  {
    slug: 'investment-calculator',
    name: 'Investment Return Calculator',
    category: 'finance',
    description: 'Calculate investment returns and growth over time',
    keywords: ['investment calculator', 'returns calculator', 'wealth calculator'],
    icon: '💎',
    faq: [],
    relatedTools: ['sip-calculator', 'cagr-calculator'],
  },

  // India Tools
  {
    slug: 'gst-calculator',
    name: 'GST Calculator',
    category: 'india',
    description: 'Calculate GST amount and price inclusive/exclusive of GST India 2026',
    keywords: ['gst calculator', 'gst india', 'goods services tax', 'india 2026'],
    icon: '🧾',
    faq: [
      { question: 'What are GST rates in India?', answer: 'GST rates in India are 0%, 5%, 12%, 18%, and 28% depending on the product or service.' },
    ],
    relatedTools: ['income-tax-calculator', 'salary-calculator'],
  },
  {
    slug: 'income-tax-calculator',
    name: 'Income Tax Calculator',
    category: 'india',
    description: 'Calculate income tax liability under new and old regime India 2026',
    keywords: ['income tax calculator', 'tax india', 'tax calculation 2026'],
    icon: '💼',
    faq: [],
    relatedTools: ['gst-calculator', 'salary-calculator'],
  },
  {
    slug: 'salary-calculator',
    name: 'Salary Calculator',
    category: 'india',
    description: 'Calculate CTC, gross salary, and net take-home salary',
    keywords: ['salary calculator', 'ctc calculator', 'take home salary'],
    icon: '💵',
    faq: [],
    relatedTools: ['income-tax-calculator', 'hra-calculator'],
  },
  {
    slug: 'pf-calculator',
    name: 'PF Calculator',
    category: 'india',
    description: 'Calculate Provident Fund contribution and maturity amount',
    keywords: ['pf calculator', 'provident fund', 'epf calculator'],
    icon: '🏦',
    faq: [],
    relatedTools: ['salary-calculator', 'fd-calculator'],
  },
  {
    slug: 'hra-calculator',
    name: 'HRA Calculator',
    category: 'india',
    description: 'Calculate House Rent Allowance tax exemption',
    keywords: ['hra calculator', 'house rent allowance', 'hra exemption'],
    icon: '🏠',
    faq: [],
    relatedTools: ['salary-calculator', 'income-tax-calculator'],
  },
  {
    slug: 'fuel-cost-calculator',
    name: 'Fuel Cost Calculator',
    category: 'india',
    description: 'Calculate fuel cost for your trip based on distance and mileage',
    keywords: ['fuel cost', 'petrol cost', 'diesel cost', 'trip cost'],
    icon: '⛽',
    faq: [],
    relatedTools: ['emi-calculator'],
  },
  {
    slug: 'take-home-salary',
    name: 'Take-Home Salary Calculator',
    category: 'india',
    description: 'Calculate actual take-home salary after all deductions',
    keywords: ['take home salary', 'net salary', 'in-hand salary'],
    icon: '💰',
    faq: [],
    relatedTools: ['salary-calculator', 'pf-calculator'],
  },

  // Student Tools
  {
    slug: 'gpa-calculator',
    name: 'GPA Calculator',
    category: 'student',
    description: 'Calculate your Grade Point Average (GPA) for semester',
    keywords: ['gpa calculator', 'grade point average', 'semester gpa'],
    icon: '🎓',
    faq: [],
    relatedTools: ['cgpa-calculator', 'marks-percentage-calculator'],
  },
  {
    slug: 'cgpa-calculator',
    name: 'CGPA Calculator',
    category: 'student',
    description: 'Calculate Cumulative GPA across all semesters',
    keywords: ['cgpa calculator', 'cumulative gpa', 'overall gpa'],
    icon: '📚',
    faq: [],
    relatedTools: ['gpa-calculator', 'marks-percentage-calculator'],
  },
  {
    slug: 'marks-percentage-calculator',
    name: 'Marks Percentage Calculator',
    category: 'student',
    description: 'Calculate percentage from marks obtained in exams',
    keywords: ['marks percentage', 'exam percentage', 'score calculator'],
    icon: '💯',
    faq: [],
    relatedTools: ['gpa-calculator', 'cgpa-calculator'],
  },
  {
    slug: 'study-time-planner',
    name: 'Study Time Planner',
    category: 'student',
    description: 'Plan your study schedule and track hours',
    keywords: ['study planner', 'study time', 'exam preparation'],
    icon: '⏰',
    faq: [],
    relatedTools: ['gpa-calculator'],
  },

  // Health & Fitness
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    category: 'health',
    description: 'Calculate Body Mass Index and check if you\'re at healthy weight',
    keywords: ['bmi calculator', 'body mass index', 'healthy weight'],
    icon: '⚖️',
    faq: [
      { question: 'What is a healthy BMI?', answer: 'A healthy BMI range is typically between 18.5 and 24.9.' },
    ],
    relatedTools: ['bmr-calculator', 'calorie-calculator'],
  },
  {
    slug: 'bmr-calculator',
    name: 'BMR Calculator',
    category: 'health',
    description: 'Calculate Basal Metabolic Rate and daily calorie needs',
    keywords: ['bmr calculator', 'basal metabolic rate', 'calorie needs'],
    icon: '🔥',
    faq: [],
    relatedTools: ['bmi-calculator', 'calorie-calculator'],
  },
  {
    slug: 'calorie-calculator',
    name: 'Calorie Calculator',
    category: 'health',
    description: 'Calculate daily calorie intake for weight loss or gain',
    keywords: ['calorie calculator', 'daily calories', 'weight loss'],
    icon: '🍎',
    faq: [],
    relatedTools: ['bmi-calculator', 'water-intake-calculator'],
  },
  {
    slug: 'water-intake-calculator',
    name: 'Water Intake Calculator',
    category: 'health',
    description: 'Calculate daily water intake based on weight and activity level',
    keywords: ['water intake', 'daily water', 'hydration calculator'],
    icon: '💧',
    faq: [],
    relatedTools: ['bmi-calculator', 'calorie-calculator'],
  },
  {
    slug: 'ideal-weight-calculator',
    name: 'Ideal Weight Calculator',
    category: 'health',
    description: 'Calculate your ideal body weight based on height',
    keywords: ['ideal weight', 'healthy weight', 'body weight'],
    icon: '🎯',
    faq: [],
    relatedTools: ['bmi-calculator', 'bmr-calculator'],
  },

  // Fun Tools
  {
    slug: 'love-calculator',
    name: 'Love Calculator',
    category: 'fun',
    description: 'Calculate love compatibility percentage between two names',
    keywords: ['love calculator', 'compatibility', 'relationship test'],
    icon: '❤️',
    faq: [],
    relatedTools: ['random-number-generator'],
  },
  {
    slug: 'random-number-generator',
    name: 'Random Number Generator',
    category: 'fun',
    description: 'Generate random numbers within your specified range',
    keywords: ['random number', 'number generator', 'rng'],
    icon: '🎲',
    faq: [],
    relatedTools: ['dice-roller', 'password-generator'],
  },
  {
    slug: 'dice-roller',
    name: 'Dice Roller',
    category: 'fun',
    description: 'Roll virtual dice with customizable number of dice and sides',
    keywords: ['dice roller', 'virtual dice', 'roll dice'],
    icon: '🎲',
    faq: [],
    relatedTools: ['random-number-generator'],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    category: 'fun',
    description: 'Generate strong, secure random passwords',
    keywords: ['password generator', 'secure password', 'random password'],
    icon: '🔐',
    faq: [],
    relatedTools: ['random-number-generator'],
  },

  // Unit Converters
  {
    slug: 'length-converter',
    name: 'Length Converter',
    category: 'converter',
    description: 'Convert between meters, kilometers, miles, feet, inches, and more',
    keywords: ['length converter', 'meter to feet', 'km to miles'],
    icon: '📏',
    faq: [],
    relatedTools: ['weight-converter', 'area-converter'],
  },
  {
    slug: 'weight-converter',
    name: 'Weight Converter',
    category: 'converter',
    description: 'Convert between kilograms, pounds, grams, ounces, and more',
    keywords: ['weight converter', 'kg to lbs', 'pounds to kilograms'],
    icon: '⚖️',
    faq: [],
    relatedTools: ['length-converter', 'volume-converter'],
  },
  {
    slug: 'temperature-converter',
    name: 'Temperature Converter',
    category: 'converter',
    description: 'Convert between Celsius, Fahrenheit, and Kelvin',
    keywords: ['temperature converter', 'celsius to fahrenheit', 'fahrenheit to celsius'],
    icon: '🌡️',
    faq: [],
    relatedTools: ['length-converter'],
  },
  {
    slug: 'currency-converter',
    name: 'Currency Converter',
    category: 'converter',
    description: 'Convert between USD, EUR, INR, GBP, and major currencies',
    keywords: ['currency converter', 'usd to inr', 'euro to dollar'],
    icon: '💱',
    faq: [],
    relatedTools: ['length-converter'],
  },
  {
    slug: 'speed-converter',
    name: 'Speed Converter',
    category: 'converter',
    description: 'Convert between km/h, mph, m/s, knots, and more',
    keywords: ['speed converter', 'kmh to mph', 'meters per second'],
    icon: '🚀',
    faq: [],
    relatedTools: ['length-converter', 'temperature-converter'],
  },
  {
    slug: 'area-converter',
    name: 'Area Converter',
    category: 'converter',
    description: 'Convert between square meters, square feet, acres, hectares',
    keywords: ['area converter', 'sq ft to sq m', 'acres to hectares'],
    icon: '📐',
    faq: [],
    relatedTools: ['length-converter', 'volume-converter'],
  },
  {
    slug: 'volume-converter',
    name: 'Volume Converter',
    category: 'converter',
    description: 'Convert between liters, gallons, milliliters, cups, and more',
    keywords: ['volume converter', 'liters to gallons', 'ml to cups'],
    icon: '🧪',
    faq: [],
    relatedTools: ['weight-converter', 'area-converter'],
  },

  // Advanced
  {
    slug: 'cagr-calculator',
    name: 'CAGR Calculator',
    category: 'advanced',
    description: 'Calculate Compound Annual Growth Rate for investments',
    keywords: ['cagr calculator', 'compound annual growth rate', 'investment growth'],
    icon: '📊',
    faq: [],
    relatedTools: ['compound-interest-calculator', 'investment-calculator'],
  },
  {
    slug: 'inflation-calculator',
    name: 'Inflation Calculator',
    category: 'advanced',
    description: 'Calculate the effect of inflation on purchasing power over time',
    keywords: ['inflation calculator', 'purchasing power', 'inflation rate'],
    icon: '📉',
    faq: [],
    relatedTools: ['cagr-calculator', 'investment-calculator'],
  },
  {
    slug: 'percentage-change-calculator',
    name: 'Percentage Change Calculator',
    category: 'advanced',
    description: 'Calculate percentage increase or decrease between two values',
    keywords: ['percentage change', 'percent increase', 'percent decrease'],
    icon: '📈',
    faq: [],
    relatedTools: ['percentage-calculator'],
  },
  {
    slug: 'roi-calculator',
    name: 'ROI Calculator',
    category: 'advanced',
    description: 'Calculate Return on Investment percentage and profit',
    keywords: ['roi calculator', 'return on investment', 'investment returns'],
    icon: '💹',
    faq: [],
    relatedTools: ['cagr-calculator', 'investment-calculator'],
  },
  {
    slug: 'birthday-countdown',
    name: 'Birthday Countdown',
    category: 'basic',
    description: 'Countdown days until your next birthday',
    keywords: ['birthday countdown', 'days until birthday', 'birthday timer'],
    icon: '🎉',
    faq: [],
    relatedTools: ['age-calculator', 'date-difference'],
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find(tool => tool.slug === slug);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter(tool => tool.category === category);
}

export function getAllSlugs(): string[] {
  return tools.map(tool => tool.slug);
}
