export interface Tool {
  slug: string;
  name: string;
  category: string;
  description: string;
  keywords: string[];
  icon: string;
  faq: { question: string; answer: string }[];
  relatedTools: string[];
}

export const categories = [
  { id: 'basic', name: 'Basic Calculators', icon: '🔢' },
  { id: 'finance', name: 'Finance Calculators', icon: '💰' },
  { id: 'india', name: 'India Tools', icon: '🇮🇳' },
  { id: 'student', name: 'Student Tools', icon: '📚' },
  { id: 'health', name: 'Health & Fitness', icon: '💪' },
  { id: 'fun', name: 'Fun Tools', icon: '🎉' },
  { id: 'converter', name: 'Unit Converters', icon: '🔄' },
  { id: 'advanced', name: 'Advanced', icon: '📊' },
];

export const tools: Tool[] = [
  // Basic Calculators
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    category: 'basic',
    description: 'Free online age calculator 2026 — calculate your exact age in years, months, and days from your date of birth. Instant and accurate results.',
    keywords: ['age calculator', 'exact age', 'age today', 'date of birth', 'online age calculator free', 'free age calculator 2026', 'current year 2026 age calculator', 'calculate age online', 'age calculation in online', 'age ca', 'age', 'online cal', 'calcager', 'free online age calculator', 'age calculator in online', 'age calculation'],
    icon: '🎂',
    faq: [
      { question: 'How is age calculated?', answer: 'Age is calculated by finding the difference between your birth date and today\'s date in years, months, and days, accounting for leap years and different month lengths.' },
      { question: 'Can I calculate age for any date?', answer: 'Yes, you can calculate age for any past or future date by entering both the birth date and the target date.' },
      { question: 'What is the age calculator 2026?', answer: 'Our Age Calculator 2026 is updated for the current year and calculates your exact age as of any date in 2026, accounting for all calendar rules.' },
      { question: 'How do I calculate my age online for free?', answer: 'Simply enter your date of birth in our free online age calculator and click Calculate. Your exact age in years, months, and days will appear instantly.' },
    ],
    relatedTools: ['date-difference', 'birthday-countdown', 'time-calculator'],
  },
  {
    slug: 'percentage-calculator',
    name: 'Percentage Calculator',
    category: 'basic',
    description: 'Free online percentage calculator — find what percent one number is of another, calculate X% of Y, and solve percentage problems instantly.',
    keywords: ['percentage calculator', 'percent calculation', 'what percent', 'percentage formula', 'calculate percentage', 'percentage math', '15% of 49', '2 out of 36 as a percentage', 'how to add and subtract percentages', 'percentage difference formula', 'free online percentage calculator', 'formula to calculate percentage'],
    icon: '💯',
    faq: [
      { question: 'How to calculate percentage?', answer: 'Divide the part by the whole and multiply by 100. For example, 15 out of 60 = (15/60) × 100 = 25%.' },
      { question: 'How do I find what percent one number is of another?', answer: 'Divide the first number by the second and multiply by 100. Example: 12 out of 40 = (12/40) × 100 = 30%.' },
      { question: 'What is the formula to calculate percentage?', answer: 'Percentage = (Part / Whole) × 100. Use our free calculator for instant results.' },
      { question: 'How to add and subtract percentages?', answer: 'To add 20% to 100: 100 + (100 × 0.20) = 120. To subtract 20% from 100: 100 - (100 × 0.20) = 80.' },
    ],
    relatedTools: ['percentage-change-calculator', 'discount-calculator', 'profit-loss-calculator'],
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    category: 'basic',
    description: 'Calculate discount amount and final price after discount',
    keywords: ['discount calculator', 'sale price', 'discount percentage'],
    icon: '🏷️',
    faq: [],
    relatedTools: ['percentage-calculator', 'profit-loss-calculator'],
  },
  {
    slug: 'profit-loss-calculator',
    name: 'Profit & Loss Calculator',
    category: 'basic',
    description: 'Calculate profit or loss percentage and amount',
    keywords: ['profit calculator', 'loss calculator', 'profit margin'],
    icon: '📈',
    faq: [],
    relatedTools: ['percentage-calculator', 'discount-calculator'],
  },
  {
    slug: 'average-calculator',
    name: 'Average Calculator',
    category: 'basic',
    description: 'Calculate the average (mean) of multiple numbers',
    keywords: ['average calculator', 'mean calculator', 'average of numbers'],
    icon: '📊',
    faq: [],
    relatedTools: ['percentage-calculator'],
  },
  {
    slug: 'ratio-calculator',
    name: 'Ratio Calculator',
    category: 'basic',
    description: 'Calculate ratios and proportions easily',
    keywords: ['ratio calculator', 'proportion calculator', 'ratio solver'],
    icon: '⚖️',
    faq: [],
    relatedTools: ['percentage-calculator'],
  },
  {
    slug: 'time-calculator',
    name: 'Time Calculator',
    category: 'basic',
    description: 'Add, subtract, and convert time durations',
    keywords: ['time calculator', 'time add', 'time difference'],
    icon: '⏰',
    faq: [],
    relatedTools: ['date-difference', 'age-calculator'],
  },
  {
    slug: 'date-difference',
    name: 'Date Difference Calculator',
    category: 'basic',
    description: 'Calculate the difference between two dates in days, weeks, months',
    keywords: ['date difference', 'days between dates', 'date calculator'],
    icon: '📅',
    faq: [],
    relatedTools: ['age-calculator', 'time-calculator'],
  },
  {
    slug: 'simple-interest-calculator',
    name: 'Simple Interest Calculator',
    category: 'basic',
    description: 'Calculate simple interest on loans and investments',
    keywords: ['simple interest', 'SI calculator', 'interest calculation'],
    icon: '💵',
    faq: [],
    relatedTools: ['compound-interest-calculator', 'emi-calculator'],
  },
  {
    slug: 'compound-interest-calculator',
    name: 'Compound Interest Calculator',
    category: 'basic',
    description: 'Free compound interest calculator — calculate compound interest with annual, monthly, or daily compounding. Includes compound formula with examples.',
    keywords: ['compound interest', 'CI calculator', 'compound growth', 'compound formula calculator', 'compound interest formula', 'compound site', 'compound finance', 'compound finance calculator', 'compounding calculator'],
    icon: '💹',
    faq: [
      { question: 'What is the compound interest formula?', answer: 'A = P × (1 + R/n)^(nT), where A=final amount, P=principal, R=annual rate (decimal), n=compounding periods per year, T=time in years.' },
      { question: 'How is compound interest different from simple interest?', answer: 'Simple interest is calculated only on principal. Compound interest is calculated on principal plus previously earned interest, growing faster over time.' },
    ],
    relatedTools: ['simple-interest-calculator', 'sip-calculator', 'fd-calculator'],
  },

  // Finance Calculators
  {
    slug: 'emi-calculator',
    name: 'EMI Calculator',
    category: 'finance',
    description: 'Calculate EMI for home loan, car loan, personal loan in India 2026',
    keywords: ['emi calculator', 'loan emi', 'monthly payment', 'india 2026'],
    icon: '🏦',
    faq: [
      { question: 'What is EMI?', answer: 'EMI (Equated Monthly Installment) is a fixed payment amount made by a borrower to a lender at a specified date each calendar month.' },
    ],
    relatedTools: ['loan-calculator', 'simple-interest-calculator'],
  },
  {
    slug: 'loan-calculator',
    name: 'Loan Calculator',
    category: 'finance',
    description: 'Calculate loan amount, interest, and total repayment',
    keywords: ['loan calculator', 'loan payment', 'borrowing calculator'],
    icon: '💳',
    faq: [],
    relatedTools: ['emi-calculator', 'simple-interest-calculator'],
  },
  {
    slug: 'sip-calculator',
    name: 'SIP Calculator',
    category: 'finance',
    description: 'Free SIP calculator India 2026 — calculate monthly Systematic Investment Plan returns, wealth gained, and mutual fund maturity amount instantly.',
    keywords: ['sip calculator', 'monthly investment', 'mutual fund returns', 'india', 'sip calculator india', 'sip investment calculator', 'systematic investment plan', 'sip returns', 'sip maturity'],
    icon: '📈',
    faq: [
      { question: 'What is SIP?', answer: 'SIP (Systematic Investment Plan) lets you invest a fixed amount in mutual funds every month. It helps in rupee cost averaging and compounding over time.' },
      { question: 'How to calculate SIP returns?', answer: 'SIP returns are calculated using compound interest formula: M = P × [(1 + r)^n - 1] / r × (1 + r), where P=monthly investment, r=monthly rate, n=months.' },
    ],
    relatedTools: ['compound-interest-calculator', 'fd-calculator', 'investment-calculator'],
  },
  {
    slug: 'fd-calculator',
    name: 'FD Calculator',
    category: 'finance',
    description: 'Free online FD calculator — calculate Fixed Deposit maturity amount, interest earned, and returns. Supports cumulative and non-cumulative FD in India.',
    keywords: ['fd calculator', 'fixed deposit', 'maturity amount', 'online fd', 'fd formula', 'fd calculation formula', 'fd cal', 'fd calc', 'fd calculator online', 'online fixed deposit calculator', 'fd calculator non cumulative', 'finance rd', 'fixed calculator', 'fd online'],
    icon: '🏛️',
    faq: [
      { question: 'What is the FD formula?', answer: 'For simple interest FD: Maturity = P + (P × R × T / 100). For compound interest: A = P × (1 + R/n)^(nT), where P=principal, R=rate, T=time, n=compounding frequency.' },
      { question: 'What is the difference between cumulative and non-cumulative FD?', answer: 'Cumulative FD reinvests interest to compound it at maturity. Non-cumulative FD pays interest periodically (monthly, quarterly). Cumulative gives higher returns.' },
      { question: 'How to calculate FD returns online?', answer: 'Enter your deposit amount, interest rate, and tenure in our FD Calculator. You will instantly see the maturity amount and total interest earned.' },
    ],
    relatedTools: ['rd-calculator', 'sip-calculator', 'compound-interest-calculator'],
  },
  {
    slug: 'rd-calculator',
    name: 'RD Calculator',
    category: 'finance',
    description: 'Free online RD calculator — calculate Recurring Deposit maturity amount, monthly interest, and total returns. RD formula with examples.',
    keywords: ['rd calculator', 'recurring deposit', 'monthly deposit', 'rd cal', 'online rd calculator', 'rd formula', 'formula for rd', 'r and d calculator', 'calculating rd', 'calculator rd', 'finance rd', 'rd calculation'],
    icon: '💰',
    faq: [
      { question: 'What is the RD formula?', answer: 'RD Maturity = P × n + P × n×(n+1)/2 × R/(12×100), where P=monthly deposit, n=months, R=annual interest rate.' },
      { question: 'How to calculate RD returns online?', answer: 'Enter your monthly deposit amount, interest rate, and tenure in our free RD Calculator for instant maturity amount results.' },
      { question: 'What is the difference between RD and FD?', answer: 'In FD you deposit a lump sum once. In RD you deposit a fixed amount every month. RD is ideal for regular savers.' },
    ],
    relatedTools: ['fd-calculator', 'sip-calculator', 'compound-interest-calculator'],
  },
  {
    slug: 'retirement-calculator',
    name: 'Retirement Calculator',
    category: 'finance',
    description: 'Plan your retirement corpus and monthly savings needed',
    keywords: ['retirement calculator', 'retirement planning', 'corpus calculation'],
    icon: '🏖️',
    faq: [],
    relatedTools: ['sip-calculator', 'investment-calculator'],
  },
  {
    slug: 'investment-calculator',
    name: 'Investment Return Calculator',
    category: 'finance',
    description: 'Calculate investment returns and growth over time',
    keywords: ['investment calculator', 'returns calculator', 'wealth calculator'],
    icon: '💎',
    faq: [],
    relatedTools: ['sip-calculator', 'cagr-calculator'],
  },

  // India Tools
  {
    slug: 'gst-calculator',
    name: 'GST Calculator',
    category: 'india',
    description: 'Calculate GST amount and price inclusive/exclusive of GST India 2026',
    keywords: ['gst calculator', 'gst india', 'goods services tax', 'india 2026'],
    icon: '🧾',
    faq: [
      { question: 'What are GST rates in India?', answer: 'GST rates in India are 0%, 5%, 12%, 18%, and 28% depending on the product or service.' },
    ],
    relatedTools: ['income-tax-calculator', 'salary-calculator'],
  },
  {
    slug: 'income-tax-calculator',
    name: 'Income Tax Calculator',
    category: 'india',
    description: 'Calculate income tax liability under new and old regime India 2026',
    keywords: ['income tax calculator', 'tax india', 'tax calculation 2026'],
    icon: '💼',
    faq: [],
    relatedTools: ['gst-calculator', 'salary-calculator'],
  },
  {
    slug: 'salary-calculator',
    name: 'Salary Calculator',
    category: 'india',
    description: 'Calculate CTC, gross salary, and net take-home salary',
    keywords: ['salary calculator', 'ctc calculator', 'take home salary'],
    icon: '💵',
    faq: [],
    relatedTools: ['income-tax-calculator', 'hra-calculator'],
  },
  {
    slug: 'pf-calculator',
    name: 'PF Calculator',
    category: 'india',
    description: 'Calculate Provident Fund contribution and maturity amount',
    keywords: ['pf calculator', 'provident fund', 'epf calculator'],
    icon: '🏦',
    faq: [],
    relatedTools: ['salary-calculator', 'fd-calculator'],
  },
  {
    slug: 'hra-calculator',
    name: 'HRA Calculator',
    category: 'india',
    description: 'Calculate House Rent Allowance tax exemption',
    keywords: ['hra calculator', 'house rent allowance', 'hra exemption'],
    icon: '🏠',
    faq: [],
    relatedTools: ['salary-calculator', 'income-tax-calculator'],
  },
  {
    slug: 'fuel-cost-calculator',
    name: 'Fuel Cost Calculator',
    category: 'india',
    description: 'Calculate fuel cost for your trip based on distance and mileage',
    keywords: ['fuel cost', 'petrol cost', 'diesel cost', 'trip cost'],
    icon: '⛽',
    faq: [],
    relatedTools: ['emi-calculator'],
  },
  {
    slug: 'take-home-salary',
    name: 'Take-Home Salary Calculator',
    category: 'india',
    description: 'Calculate actual take-home salary after all deductions',
    keywords: ['take home salary', 'net salary', 'in-hand salary'],
    icon: '💰',
    faq: [],
    relatedTools: ['salary-calculator', 'pf-calculator'],
  },

  // Student Tools
  {
    slug: 'gpa-calculator',
    name: 'GPA Calculator',
    category: 'student',
    description: 'Calculate your Grade Point Average (GPA) for semester',
    keywords: ['gpa calculator', 'grade point average', 'semester gpa'],
    icon: '🎓',
    faq: [],
    relatedTools: ['cgpa-calculator', 'marks-percentage-calculator'],
  },
  {
    slug: 'cgpa-calculator',
    name: 'CGPA Calculator',
    category: 'student',
    description: 'Calculate Cumulative GPA across all semesters',
    keywords: ['cgpa calculator', 'cumulative gpa', 'overall gpa'],
    icon: '📚',
    faq: [],
    relatedTools: ['gpa-calculator', 'marks-percentage-calculator'],
  },
  {
    slug: 'marks-percentage-calculator',
    name: 'Marks Percentage Calculator',
    category: 'student',
    description: 'Calculate percentage from marks obtained in exams',
    keywords: ['marks percentage', 'exam percentage', 'score calculator'],
    icon: '💯',
    faq: [],
    relatedTools: ['gpa-calculator', 'cgpa-calculator'],
  },
  {
    slug: 'study-time-planner',
    name: 'Study Time Planner',
    category: 'student',
    description: 'Plan your study schedule and track hours',
    keywords: ['study planner', 'study time', 'exam preparation'],
    icon: '⏰',
    faq: [],
    relatedTools: ['gpa-calculator'],
  },

  // Health & Fitness
  {
    slug: 'bmi-calculator',
    name: 'BMI Calculator',
    category: 'health',
    description: 'Free BMI calculator 2026 — calculate your Body Mass Index instantly and check if you are underweight, normal, overweight, or obese.',
    keywords: ['bmi calculator', 'body mass index', 'healthy weight', 'bmi calculator 2026', 'bmi check', 'bmi compute', 'bmi checker', 'check bmi', 'calculate bmi', 'bmi online'],
    icon: '⚖️',
    faq: [
      { question: 'What is a healthy BMI?', answer: 'A healthy BMI range is 18.5 to 24.9. Below 18.5 is underweight, 25-29.9 is overweight, and 30+ is obese.' },
      { question: 'What is the BMI formula?', answer: 'BMI = Weight (kg) / Height (m)². For example, 70kg ÷ (1.75 × 1.75) = 22.9 BMI.' },
      { question: 'Is BMI accurate for everyone?', answer: 'BMI is a general screening tool. It may not be fully accurate for athletes, elderly, or pregnant women. Always consult a doctor for health decisions.' },
    ],
    relatedTools: ['bmr-calculator', 'calorie-calculator', 'ideal-weight-calculator'],
  },
  {
    slug: 'bmr-calculator',
    name: 'BMR Calculator',
    category: 'health',
    description: 'Free BMR calculator online — calculate your Basal Metabolic Rate and daily calorie needs using the Mifflin-St Jeor equation. Perfect for weight management.',
    keywords: ['bmr calculator', 'basal metabolic rate', 'calorie needs', 'bmr calculator online', 'bmr compute', 'calculate bmr', 'bmr online', 'daily calorie needs', 'bmr formula'],
    icon: '🔥',
    faq: [
      { question: 'What is BMR?', answer: 'Basal Metabolic Rate (BMR) is the number of calories your body needs to maintain basic functions at rest (breathing, circulation, cell production).' },
      { question: 'How do I calculate my BMR?', answer: 'Men: BMR = 10W + 6.25H - 5A + 5. Women: BMR = 10W + 6.25H - 5A - 161. (W=weight kg, H=height cm, A=age years). Our calculator does this instantly.' },
    ],
    relatedTools: ['bmi-calculator', 'calorie-calculator'],
  },
  {
    slug: 'calorie-calculator',
    name: 'Calorie Calculator',
    category: 'health',
    description: 'Free online calorie calculator — calculate your daily calorie needs for weight loss, weight gain, or maintenance based on age, weight, height, and activity level.',
    keywords: ['calorie calculator', 'daily calories', 'weight loss', 'calorie calculator for weight loss', 'how to calculate daily caloric needs for weight loss', 'how to calculate daily calories for weight loss', 'calculate intake', 'daily calorie intake', 'calorie counter', 'calories per day'],
    icon: '🍎',
    faq: [
      { question: 'How do I calculate daily calorie needs for weight loss?', answer: 'Use the Mifflin-St Jeor equation to find your BMR, then multiply by your activity factor to get TDEE. Subtract 500 calories/day for ~0.5kg/week loss.' },
      { question: 'How many calories do I need per day?', answer: 'This depends on your age, sex, height, weight, and activity level. On average, women need 1600-2400 and men need 2000-3000 calories daily.' },
      { question: 'What is the best calorie intake for weight loss?', answer: 'A deficit of 500-750 calories per day from your maintenance level is safe and effective for gradual weight loss.' },
    ],
    relatedTools: ['bmi-calculator', 'bmr-calculator', 'water-intake-calculator'],
  },
  {
    slug: 'water-intake-calculator',
    name: 'Water Intake Calculator',
    category: 'health',
    description: 'Calculate daily water intake based on weight and activity level',
    keywords: ['water intake', 'daily water', 'hydration calculator'],
    icon: '💧',
    faq: [],
    relatedTools: ['bmi-calculator', 'calorie-calculator'],
  },
  {
    slug: 'ideal-weight-calculator',
    name: 'Ideal Weight Calculator',
    category: 'health',
    description: 'Calculate your ideal body weight based on height',
    keywords: ['ideal weight', 'healthy weight', 'body weight'],
    icon: '🎯',
    faq: [],
    relatedTools: ['bmi-calculator', 'bmr-calculator'],
  },

  // Fun Tools
  {
    slug: 'love-calculator',
    name: 'Love Calculator',
    category: 'fun',
    description: 'Calculate love compatibility percentage between two names',
    keywords: ['love calculator', 'compatibility', 'relationship test'],
    icon: '❤️',
    faq: [],
    relatedTools: ['random-number-generator'],
  },
  {
    slug: 'random-number-generator',
    name: 'Random Number Generator',
    category: 'fun',
    description: 'Generate random numbers within your specified range',
    keywords: ['random number', 'number generator', 'rng'],
    icon: '🎲',
    faq: [],
    relatedTools: ['dice-roller', 'password-generator'],
  },
  {
    slug: 'dice-roller',
    name: 'Dice Roller',
    category: 'fun',
    description: 'Roll virtual dice with customizable number of dice and sides',
    keywords: ['dice roller', 'virtual dice', 'roll dice'],
    icon: '🎲',
    faq: [],
    relatedTools: ['random-number-generator'],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    category: 'fun',
    description: 'Generate strong, secure random passwords',
    keywords: ['password generator', 'secure password', 'random password'],
    icon: '🔐',
    faq: [],
    relatedTools: ['random-number-generator'],
  },

  // Unit Converters
  {
    slug: 'length-converter',
    name: 'Length Converter',
    category: 'converter',
    description: 'Convert between meters, kilometers, miles, feet, inches, and more',
    keywords: ['length converter', 'meter to feet', 'km to miles'],
    icon: '📏',
    faq: [],
    relatedTools: ['weight-converter', 'area-converter'],
  },
  {
    slug: 'weight-converter',
    name: 'Weight Converter',
    category: 'converter',
    description: 'Convert between kilograms, pounds, grams, ounces, and more',
    keywords: ['weight converter', 'kg to lbs', 'pounds to kilograms'],
    icon: '⚖️',
    faq: [],
    relatedTools: ['length-converter', 'volume-converter'],
  },
  {
    slug: 'temperature-converter',
    name: 'Temperature Converter',
    category: 'converter',
    description: 'Convert between Celsius, Fahrenheit, and Kelvin',
    keywords: ['temperature converter', 'celsius to fahrenheit', 'fahrenheit to celsius'],
    icon: '🌡️',
    faq: [],
    relatedTools: ['length-converter'],
  },
  {
    slug: 'currency-converter',
    name: 'Currency Converter',
    category: 'converter',
    description: 'Convert between USD, EUR, INR, GBP, and major currencies',
    keywords: ['currency converter', 'usd to inr', 'euro to dollar'],
    icon: '💱',
    faq: [],
    relatedTools: ['length-converter'],
  },
  {
    slug: 'speed-converter',
    name: 'Speed Converter',
    category: 'converter',
    description: 'Convert between km/h, mph, m/s, knots, and more',
    keywords: ['speed converter', 'kmh to mph', 'meters per second'],
    icon: '🚀',
    faq: [],
    relatedTools: ['length-converter', 'temperature-converter'],
  },
  {
    slug: 'area-converter',
    name: 'Area Converter',
    category: 'converter',
    description: 'Convert between square meters, square feet, acres, hectares',
    keywords: ['area converter', 'sq ft to sq m', 'acres to hectares'],
    icon: '📐',
    faq: [],
    relatedTools: ['length-converter', 'volume-converter'],
  },
  {
    slug: 'volume-converter',
    name: 'Volume Converter',
    category: 'converter',
    description: 'Convert between liters, gallons, milliliters, cups, and more',
    keywords: ['volume converter', 'liters to gallons', 'ml to cups'],
    icon: '🧪',
    faq: [],
    relatedTools: ['weight-converter', 'area-converter'],
  },

  // Advanced
  {
    slug: 'cagr-calculator',
    name: 'CAGR Calculator',
    category: 'advanced',
    description: 'Free CAGR calculator — calculate Compound Annual Growth Rate for any investment. Compare growth across different time periods easily.',
    keywords: ['cagr calculator', 'compound annual growth rate', 'investment growth', 'cagr formula', 'annual growth rate', 'investment cagr'],
    icon: '📊',
    faq: [
      { question: 'What is CAGR?', answer: 'CAGR (Compound Annual Growth Rate) is the rate at which an investment grows from its beginning value to its ending value over a period, assuming profits are reinvested annually.' },
      { question: 'What is the CAGR formula?', answer: 'CAGR = (End Value / Start Value)^(1/Years) - 1. Multiply by 100 for percentage.' },
    ],
    relatedTools: ['compound-interest-calculator', 'investment-calculator', 'roi-calculator'],
  },
  {
    slug: 'inflation-calculator',
    name: 'Inflation Calculator',
    category: 'advanced',
    description: 'Calculate the effect of inflation on purchasing power over time',
    keywords: ['inflation calculator', 'purchasing power', 'inflation rate'],
    icon: '📉',
    faq: [],
    relatedTools: ['cagr-calculator', 'investment-calculator'],
  },
  {
    slug: 'percentage-change-calculator',
    name: 'Percentage Change Calculator',
    category: 'advanced',
    description: 'Free online percentage change calculator — instantly calculate percent increase or decrease between two values. Simple formula, fast results.',
    keywords: ['percentage change calculator', 'percent change calculator', 'percentage change', 'percent change', 'percent increase calculator', 'percent decrease calculator', 'calculate percent change', 'percentage change formula', 'online percent change calculator', 'pct change calculator', 'change calculator', 'percentage change calc', 'calculate percentage change', 'percent change calculation', 'percent change calculate', 'percentage changecalculator', 'percentage movement calculator', 'change as a percentage calculator', 'change in percentage calculator', 'percent of change calculator', 'percentage of change calculator', 'percent to change calculator', 'percentage change calculator online', 'calculate percentage change calculator', 'change formula calculator', 'percent change calculator formula', 'best free percentage calculator online'],
    icon: '📈',
    faq: [
      { question: 'What is the percentage change formula?', answer: 'Percentage Change = ((New Value - Old Value) / |Old Value|) × 100. A positive result means an increase, negative means a decrease.' },
      { question: 'How to calculate percent change?', answer: 'Subtract the old value from the new value, divide by the old value, then multiply by 100. Example: from 50 to 75 = ((75-50)/50) × 100 = 50% increase.' },
      { question: 'What is the difference between percentage change and percentage difference?', answer: 'Percentage change measures the change from an original value. Percentage difference measures the difference between two values relative to their average.' },
      { question: 'How do I calculate a decrease in percentage?', answer: 'Use the same formula: ((New - Old) / Old) × 100. A negative result indicates a percentage decrease.' },
      { question: 'Can I use this for price changes?', answer: 'Yes! Enter the old price as the original value and new price as the new value to instantly calculate price increase or decrease percentage.' },
    ],
    relatedTools: ['percentage-calculator', 'roi-calculator', 'profit-loss-calculator'],
  },
  {
    slug: 'roi-calculator',
    name: 'ROI Calculator',
    category: 'advanced',
    description: 'Free online ROI calculator — calculate Return on Investment percentage, profit, and net gain instantly. Ideal for business and investment decisions.',
    keywords: ['roi calculator', 'return on investment', 'investment returns', 'online roi', 'online roi calculator', 'roi calculators', 'calculator roi', 'roi formula calculator', 'roi calc', 'calculate roi', 'return on investment calculator', 'investment roi'],
    icon: '💹',
    faq: [
      { question: 'What is ROI?', answer: 'ROI (Return on Investment) measures the gain or loss generated on an investment relative to the amount invested. ROI = ((Gain - Cost) / Cost) × 100.' },
      { question: 'What is a good ROI?', answer: 'A good ROI depends on the investment type. For stocks, 7-10% annual is considered good. For business investments, 15-20%+ is typical.' },
      { question: 'How to calculate ROI percentage?', answer: 'ROI % = ((Net Profit / Cost of Investment) × 100). Enter your investment cost and returns in our calculator for an instant result.' },
    ],
    relatedTools: ['cagr-calculator', 'investment-calculator', 'percentage-change-calculator'],
  },
  {
    slug: 'birthday-countdown',
    name: 'Birthday Countdown',
    category: 'basic',
    description: 'Countdown days until your next birthday',
    keywords: ['birthday countdown', 'days until birthday', 'birthday timer'],
    icon: '🎉',
    faq: [],
    relatedTools: ['age-calculator', 'date-difference'],
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find(tool => tool.slug === slug);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter(tool => tool.category === category);
}

export function getAllSlugs(): string[] {
  return tools.map(tool => tool.slug);
}
